version: "3.8"

services:
  backend:
    build: ./meidesaqua-backend-master
    container_name: meidesaqua-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/meis_de_saqua?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root # ALTERADO
      - SPRING_DATASOURCE_PASSWORD=samuel123 # ALTERADO
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

  frontend:
    build: ./MeideSaqua-main
    container_name: meidesaqua-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    restart: always

  db:
    image: mysql:8.0
    container_name: meidesaqua-db
    restart: always
    environment:
      MYSQL_DATABASE: meis_de_saqua
      MYSQL_USER: root
      MYSQL_PASSWORD: samuel123
      MYSQL_ROOT_PASSWORD: root_password_muito_segura
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: